// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docs: [
        {
            type: 'doc',
            id: 'intro',
        },
        {
            type: 'doc',
            id: 'installation',
        },
        {
            type: 'category',
            label: 'Tutorials',
            items: [{ type: 'autogenerated', dirName: 'Tutorials' }],
        },
        {
            type: 'category',
            label: 'Examples',
            items: [{ type: 'autogenerated', dirName: 'Examples' }],
        },
        {
            type: 'category',
            collapsible: false,
            items: [{ type: 'autogenerated', dirName: 'Components' }],
            label: 'Components',
        },
        {
            type: 'category',
            collapsible: false,
            items: [{ type: 'autogenerated', dirName: 'Hooks' }],
            label: 'Hooks',
        },
    ],
};

module.exports = sidebars;
